#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: ac7v4
#=================================================

name: Build_ArcherC7v4

on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex node-uglify git gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/openwrt/openwrt
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
    - name: Add PR https://github.com/openwrt/openwrt/pull/4036
      env: 
        PR_4036_REPO_URL: https://github.com/Ansuel/openwrt.git
        PR_4036_REPO_BRANCH: ipq806x-5.10-dsa
      working-directory: ./openwrt
      run: |
        git pull --no-rebase $PR_4036_REPO_URL $PR_4036_REPO_BRANCH --allow-unrelated-histories
    - name: Add PR https://github.com/openwrt/openwrt/pull/4528
      env: 
        PR_4528_REPO_URL: https://github.com/clayface/openwrt.git
        PR_4528_REPO_BRANCH: qca8k-backport
      working-directory: ./openwrt
      run: |
        git pull --no-rebase $PR_4528_REPO_URL $PR_4528_REPO_BRANCH --allow-unrelated-histories
    - name: Add PR https://github.com/openwrt/openwrt/pull/4622
      env: 
        PR_4622_REPO_URL: https://github.com/neheb/openwrt.git
        PR_4622_REPO_BRANCH: ath79-dsa
      working-directory: ./openwrt
      run: |
        git pull --no-rebase $PR_4622_REPO_URL $PR_4622_REPO_BRANCH --allow-unrelated-histories
    - name: Add PR https://github.com/openwrt/openwrt/pull/4562
      env: 
        PR_4562_REPO_URL: https://github.com/Ansuel/openwrt.git
        PR_4562_REPO_BRANCH: dsa-qca8k-leds
      working-directory: ./openwrt
      run: |
        git pull --no-rebase $PR_4562_REPO_URL $PR_4562_REPO_BRANCH --allow-unrelated-histories
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        
    - name: Configuration Customization - Build_ArcherC7v4
      env:
        CONFIG_FILE: 'ArcherC7v4.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
